### ISSUE TITLE
Unable to infer complex closure return type; add explicit type to disambiguate

### ISSUE THREAD

**Issue by TheLDB** [pranavkarthik10/DiscordSwfitUI#2]
Getting the error 'Unable to infer complex closure return type; add explicit type to disambiguate' on the NavigationView on line 15 of ContentView.swift. I think that's also causing 6 Use of unresolved identifier 'Label' errors as well. Sorry if this is an easy fix I don't deal with SwiftUI very often 
![Screen Shot 2020-07-12 at 4 58 26 PM](https://user-images.githubusercontent.com/29960599/87258461-e8cee880-c460-11ea-9fbb-ca6f575f3f40.png)

**Comment by pranavkarthik10** [comment]
The Label view type is new, and is part of the new SwiftUI. Are you running Xcode 12? It should only work using Xcode 12.

**Comment by TheLDB** [comment]
> The Label view type is new, and is part of the new SwiftUI. Are you running Xcode 12? It should only work using Xcode 12.

Oh my bad, for some reason Xcode opened Xcode 11 for no reason despite Xcode 12 being my default, thank you so much
